//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:23:58 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.territory.classes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dDistrict.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dDistrict">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="р-н"/>
 *     &lt;enumeration value="у"/>
 *     &lt;enumeration value="тер"/>
 *     &lt;enumeration value="кожуун"/>
 *     &lt;enumeration value="АО"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dDistrict")
@XmlEnum
public enum DDistrict {


    /**
     * Район
     * 
     */
    @XmlEnumValue("\u0440-\u043d")
    Р_Н("\u0440-\u043d"),

    /**
     * Улус
     * 
     */
    @XmlEnumValue("\u0443")
    У("\u0443"),

    /**
     * Территория
     * 
     */
    @XmlEnumValue("\u0442\u0435\u0440")
    ТЕР("\u0442\u0435\u0440"),

    /**
     * Кожуун
     * 
     */
    @XmlEnumValue("\u043a\u043e\u0436\u0443\u0443\u043d")
    КОЖУУН("\u043a\u043e\u0436\u0443\u0443\u043d"),

    /**
     * Автономный округ
     * 
     */
    АО("\u0410\u041e");
    private final String value;

    DDistrict(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DDistrict fromValue(String v) {
        for (DDistrict c: DDistrict.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
