//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:23:58 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.territory.classes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dLocationLevel1Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dLocationLevel1Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="д"/>
 *     &lt;enumeration value="ГСК"/>
 *     &lt;enumeration value="казарма"/>
 *     &lt;enumeration value="уч"/>
 *     &lt;enumeration value="вл"/>
 *     &lt;enumeration value="бокс"/>
 *     &lt;enumeration value="в/ч"/>
 *     &lt;enumeration value="сооружение"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dLocationLevel1Type")
@XmlEnum
public enum DLocationLevel1Type {


    /**
     * Дом
     * 
     */
    @XmlEnumValue("\u0434")
    Д("\u0434"),

    /**
     * Гаражно-строительный кооператив
     * 
     */
    ГСК("\u0413\u0421\u041a"),

    /**
     * казарма
     * 
     */
    @XmlEnumValue("\u043a\u0430\u0437\u0430\u0440\u043c\u0430")
    КАЗАРМА("\u043a\u0430\u0437\u0430\u0440\u043c\u0430"),

    /**
     * Участок
     * 
     */
    @XmlEnumValue("\u0443\u0447")
    УЧ("\u0443\u0447"),

    /**
     * Владение
     * 
     */
    @XmlEnumValue("\u0432\u043b")
    ВЛ("\u0432\u043b"),

    /**
     * бокс
     * 
     */
    @XmlEnumValue("\u0431\u043e\u043a\u0441")
    БОКС("\u0431\u043e\u043a\u0441"),

    /**
     * военная часть
     * 
     */
    @XmlEnumValue("\u0432/\u0447")
    В_Ч("\u0432/\u0447"),

    /**
     * сооружение
     * 
     */
    @XmlEnumValue("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435")
    СООРУЖЕНИЕ("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435");
    private final String value;

    DLocationLevel1Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DLocationLevel1Type fromValue(String v) {
        for (DLocationLevel1Type c: DLocationLevel1Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
