//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:23:58 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.territory.classes;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Координата
 * 
 * <p>Java class for tOrdinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOrdinate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="X" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="38"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Y" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="38"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Z">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="38"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Ord_Nmb" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="22"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Num_Geopoint" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Geopoint_Zacrep" type="{}dGeopoint_Zacrep" />
 *       &lt;attribute name="Geopoint_Opred" type="{}dGeopoint_Opred" />
 *       &lt;attribute name="Delta_Geopoint">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Point_Pref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOrdinate")
@XmlSeeAlso({
    org.tomskgislab.vertex.xml.zem.territory.classes.TSPELEMENTUNIT.Ordinate.class
})
public class TOrdinate {

    @XmlAttribute(name = "X", required = true)
    protected BigDecimal x;
    @XmlAttribute(name = "Y", required = true)
    protected BigDecimal y;
    @XmlAttribute(name = "Z")
    protected BigDecimal z;
    @XmlAttribute(name = "Ord_Nmb", required = true)
    protected BigInteger ordNmb;
    @XmlAttribute(name = "Num_Geopoint")
    protected BigInteger numGeopoint;
    @XmlAttribute(name = "Geopoint_Zacrep")
    protected String geopointZacrep;
    @XmlAttribute(name = "Geopoint_Opred")
    protected String geopointOpred;
    @XmlAttribute(name = "Delta_Geopoint")
    protected BigDecimal deltaGeopoint;
    @XmlAttribute(name = "Point_Pref")
    protected String pointPref;

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setX(BigDecimal value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setY(BigDecimal value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZ(BigDecimal value) {
        this.z = value;
    }

    /**
     * Gets the value of the ordNmb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdNmb() {
        return ordNmb;
    }

    /**
     * Sets the value of the ordNmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdNmb(BigInteger value) {
        this.ordNmb = value;
    }

    /**
     * Gets the value of the numGeopoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumGeopoint() {
        return numGeopoint;
    }

    /**
     * Sets the value of the numGeopoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumGeopoint(BigInteger value) {
        this.numGeopoint = value;
    }

    /**
     * Gets the value of the geopointZacrep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeopointZacrep() {
        return geopointZacrep;
    }

    /**
     * Sets the value of the geopointZacrep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeopointZacrep(String value) {
        this.geopointZacrep = value;
    }

    /**
     * Gets the value of the geopointOpred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeopointOpred() {
        return geopointOpred;
    }

    /**
     * Sets the value of the geopointOpred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeopointOpred(String value) {
        this.geopointOpred = value;
    }

    /**
     * Gets the value of the deltaGeopoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeltaGeopoint() {
        return deltaGeopoint;
    }

    /**
     * Sets the value of the deltaGeopoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeltaGeopoint(BigDecimal value) {
        this.deltaGeopoint = value;
    }

    /**
     * Gets the value of the pointPref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointPref() {
        return pointPref;
    }

    /**
     * Sets the value of the pointPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointPref(String value) {
        this.pointPref = value;
    }

}
