//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:23:58 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.territory.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Владелец 
 * 
 * <p>Java class for tOwner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOwner">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Person">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}tPerson">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Organization">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}tOrganization">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Governance" type="{}tGovernance"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOwner", propOrder = {
    "person",
    "organization",
    "governance"
})
@XmlSeeAlso({
    org.tomskgislab.vertex.xml.zem.territory.classes.BoundToGKN.RequestBoundToGKN.Declarant.class
})
public class TOwner {

    @XmlElement(name = "Person")
    protected TOwner.Person person;
    @XmlElement(name = "Organization")
    protected TOwner.Organization organization;
    @XmlElement(name = "Governance")
    protected TGovernance governance;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link TOwner.Person }
     *     
     */
    public TOwner.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOwner.Person }
     *     
     */
    public void setPerson(TOwner.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link TOwner.Organization }
     *     
     */
    public TOwner.Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOwner.Organization }
     *     
     */
    public void setOrganization(TOwner.Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the governance property.
     * 
     * @return
     *     possible object is
     *     {@link TGovernance }
     *     
     */
    public TGovernance getGovernance() {
        return governance;
    }

    /**
     * Sets the value of the governance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGovernance }
     *     
     */
    public void setGovernance(TGovernance value) {
        this.governance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}tOrganization">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Organization
        extends TOrganization
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}tPerson">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Person
        extends TPerson
    {


    }

}
