//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:25:35 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.zone.classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tomskgislab.vertex.xml.zem.zone.classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tomskgislab.vertex.xml.zem.zone.classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntitySpatial }
     * 
     */
    public EntitySpatial createEntitySpatial() {
        return new EntitySpatial();
    }

    /**
     * Create an instance of {@link ZoneToGKN }
     * 
     */
    public ZoneToGKN createZoneToGKN() {
        return new ZoneToGKN();
    }

    /**
     * Create an instance of {@link TOwner }
     * 
     */
    public TOwner createTOwner() {
        return new TOwner();
    }

    /**
     * Create an instance of {@link TTerritorialZone }
     * 
     */
    public TTerritorialZone createTTerritorialZone() {
        return new TTerritorialZone();
    }

    /**
     * Create an instance of {@link TTerritorialZone.PermittedUses }
     * 
     */
    public TTerritorialZone.PermittedUses createTTerritorialZonePermittedUses() {
        return new TTerritorialZone.PermittedUses();
    }

    /**
     * Create an instance of {@link TSPELEMENTUNIT }
     * 
     */
    public TSPELEMENTUNIT createTSPELEMENTUNIT() {
        return new TSPELEMENTUNIT();
    }

    /**
     * Create an instance of {@link TDocument }
     * 
     */
    public TDocument createTDocument() {
        return new TDocument();
    }

    /**
     * Create an instance of {@link TDocument.Images }
     * 
     */
    public TDocument.Images createTDocumentImages() {
        return new TDocument.Images();
    }

    /**
     * Create an instance of {@link TBorder }
     * 
     */
    public TBorder createTBorder() {
        return new TBorder();
    }

    /**
     * Create an instance of {@link TBorder.Edge }
     * 
     */
    public TBorder.Edge createTBorderEdge() {
        return new TBorder.Edge();
    }

    /**
     * Create an instance of {@link TBorder.Edge.Neighbours }
     * 
     */
    public TBorder.Edge.Neighbours createTBorderEdgeNeighbours() {
        return new TBorder.Edge.Neighbours();
    }

    /**
     * Create an instance of {@link TAddress }
     * 
     */
    public TAddress createTAddress() {
        return new TAddress();
    }

    /**
     * Create an instance of {@link TTitle }
     * 
     */
    public TTitle createTTitle() {
        return new TTitle();
    }

    /**
     * Create an instance of {@link TTitle.CurrentChanges }
     * 
     */
    public TTitle.CurrentChanges createTTitleCurrentChanges() {
        return new TTitle.CurrentChanges();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN createZoneToGKNRequestZoneToGKN() {
        return new ZoneToGKN.RequestZoneToGKN();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Zones }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Zones createZoneToGKNRequestZoneToGKNZones() {
        return new ZoneToGKN.RequestZoneToGKN.Zones();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Zones.Zone createZoneToGKNRequestZoneToGKNZonesZone() {
        return new ZoneToGKN.RequestZoneToGKN.Zones.Zone();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents createZoneToGKNRequestZoneToGKNZonesZoneDocuments() {
        return new ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Declarant }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Declarant createZoneToGKNRequestZoneToGKNDeclarant() {
        return new ZoneToGKN.RequestZoneToGKN.Declarant();
    }

    /**
     * Create an instance of {@link EntitySpatial.Borders }
     * 
     */
    public EntitySpatial.Borders createEntitySpatialBorders() {
        return new EntitySpatial.Borders();
    }

    /**
     * Create an instance of {@link TSPATIALELEMENT }
     * 
     */
    public TSPATIALELEMENT createTSPATIALELEMENT() {
        return new TSPATIALELEMENT();
    }

    /**
     * Create an instance of {@link org.tomskgislab.vertex.xml.zem.zone.classes.CoordSystems }
     * 
     */
    public org.tomskgislab.vertex.xml.zem.zone.classes.CoordSystems createCoordSystems() {
        return new org.tomskgislab.vertex.xml.zem.zone.classes.CoordSystems();
    }

    /**
     * Create an instance of {@link CoordSystem }
     * 
     */
    public CoordSystem createCoordSystem() {
        return new CoordSystem();
    }

    /**
     * Create an instance of {@link TDIMPARM }
     * 
     */
    public TDIMPARM createTDIMPARM() {
        return new TDIMPARM();
    }

    /**
     * Create an instance of {@link ZoneToGKN.EDocument }
     * 
     */
    public ZoneToGKN.EDocument createZoneToGKNEDocument() {
        return new ZoneToGKN.EDocument();
    }

    /**
     * Create an instance of {@link TCadastralNumber }
     * 
     */
    public TCadastralNumber createTCadastralNumber() {
        return new TCadastralNumber();
    }

    /**
     * Create an instance of {@link TSpecialZones }
     * 
     */
    public TSpecialZones createTSpecialZones() {
        return new TSpecialZones();
    }

    /**
     * Create an instance of {@link TGovernance }
     * 
     */
    public TGovernance createTGovernance() {
        return new TGovernance();
    }

    /**
     * Create an instance of {@link TQuantity }
     * 
     */
    public TQuantity createTQuantity() {
        return new TQuantity();
    }

    /**
     * Create an instance of {@link TPerson }
     * 
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link TOrdinate }
     * 
     */
    public TOrdinate createTOrdinate() {
        return new TOrdinate();
    }

    /**
     * Create an instance of {@link TFIO }
     * 
     */
    public TFIO createTFIO() {
        return new TFIO();
    }

    /**
     * Create an instance of {@link TOrganization }
     * 
     */
    public TOrganization createTOrganization() {
        return new TOrganization();
    }

    /**
     * Create an instance of {@link TOwner.Person }
     * 
     */
    public TOwner.Person createTOwnerPerson() {
        return new TOwner.Person();
    }

    /**
     * Create an instance of {@link TOwner.Organization }
     * 
     */
    public TOwner.Organization createTOwnerOrganization() {
        return new TOwner.Organization();
    }

    /**
     * Create an instance of {@link TTerritorialZone.LimitSize }
     * 
     */
    public TTerritorialZone.LimitSize createTTerritorialZoneLimitSize() {
        return new TTerritorialZone.LimitSize();
    }

    /**
     * Create an instance of {@link TTerritorialZone.PermittedUses.PermittedUse }
     * 
     */
    public TTerritorialZone.PermittedUses.PermittedUse createTTerritorialZonePermittedUsesPermittedUse() {
        return new TTerritorialZone.PermittedUses.PermittedUse();
    }

    /**
     * Create an instance of {@link TSPELEMENTUNIT.Ordinate }
     * 
     */
    public TSPELEMENTUNIT.Ordinate createTSPELEMENTUNITOrdinate() {
        return new TSPELEMENTUNIT.Ordinate();
    }

    /**
     * Create an instance of {@link TDocument.Duration }
     * 
     */
    public TDocument.Duration createTDocumentDuration() {
        return new TDocument.Duration();
    }

    /**
     * Create an instance of {@link TDocument.Images.Image }
     * 
     */
    public TDocument.Images.Image createTDocumentImagesImage() {
        return new TDocument.Images.Image();
    }

    /**
     * Create an instance of {@link TBorder.Edge.DirectionAngle }
     * 
     */
    public TBorder.Edge.DirectionAngle createTBorderEdgeDirectionAngle() {
        return new TBorder.Edge.DirectionAngle();
    }

    /**
     * Create an instance of {@link TBorder.Edge.Neighbours.CadastralNumber }
     * 
     */
    public TBorder.Edge.Neighbours.CadastralNumber createTBorderEdgeNeighboursCadastralNumber() {
        return new TBorder.Edge.Neighbours.CadastralNumber();
    }

    /**
     * Create an instance of {@link TAddress.District }
     * 
     */
    public TAddress.District createTAddressDistrict() {
        return new TAddress.District();
    }

    /**
     * Create an instance of {@link TAddress.City }
     * 
     */
    public TAddress.City createTAddressCity() {
        return new TAddress.City();
    }

    /**
     * Create an instance of {@link TAddress.UrbanDistrict }
     * 
     */
    public TAddress.UrbanDistrict createTAddressUrbanDistrict() {
        return new TAddress.UrbanDistrict();
    }

    /**
     * Create an instance of {@link TAddress.SovietVillage }
     * 
     */
    public TAddress.SovietVillage createTAddressSovietVillage() {
        return new TAddress.SovietVillage();
    }

    /**
     * Create an instance of {@link TAddress.Locality }
     * 
     */
    public TAddress.Locality createTAddressLocality() {
        return new TAddress.Locality();
    }

    /**
     * Create an instance of {@link TAddress.Street }
     * 
     */
    public TAddress.Street createTAddressStreet() {
        return new TAddress.Street();
    }

    /**
     * Create an instance of {@link TAddress.Level1 }
     * 
     */
    public TAddress.Level1 createTAddressLevel1() {
        return new TAddress.Level1();
    }

    /**
     * Create an instance of {@link TAddress.Level2 }
     * 
     */
    public TAddress.Level2 createTAddressLevel2() {
        return new TAddress.Level2();
    }

    /**
     * Create an instance of {@link TAddress.Level3 }
     * 
     */
    public TAddress.Level3 createTAddressLevel3() {
        return new TAddress.Level3();
    }

    /**
     * Create an instance of {@link TAddress.Apartment }
     * 
     */
    public TAddress.Apartment createTAddressApartment() {
        return new TAddress.Apartment();
    }

    /**
     * Create an instance of {@link TTitle.CurrentChanges.CurChange }
     * 
     */
    public TTitle.CurrentChanges.CurChange createTTitleCurrentChangesCurChange() {
        return new TTitle.CurrentChanges.CurChange();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.CoordSystems }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.CoordSystems createZoneToGKNRequestZoneToGKNCoordSystems() {
        return new ZoneToGKN.RequestZoneToGKN.CoordSystems();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document createZoneToGKNRequestZoneToGKNZonesZoneDocumentsDocument() {
        return new ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document();
    }

    /**
     * Create an instance of {@link ZoneToGKN.RequestZoneToGKN.Declarant.Agent }
     * 
     */
    public ZoneToGKN.RequestZoneToGKN.Declarant.Agent createZoneToGKNRequestZoneToGKNDeclarantAgent() {
        return new ZoneToGKN.RequestZoneToGKN.Declarant.Agent();
    }

    /**
     * Create an instance of {@link EntitySpatial.Borders.Border }
     * 
     */
    public EntitySpatial.Borders.Border createEntitySpatialBordersBorder() {
        return new EntitySpatial.Borders.Border();
    }

}
