//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:25:35 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.zone.classes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Территориальная зона
 * 
 * <p>Java class for tTerritorialZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTerritorialZone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PermittedUses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PermittedUse" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TypePermittedUse" type="{}dPermitUse"/>
 *                             &lt;element name="LandUse" type="{}dUtilizations" minOccurs="0"/>
 *                             &lt;element name="PermittedUse">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="4000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LimitSize" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Max" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="Min" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTerritorialZone", propOrder = {
    "permittedUses",
    "limitSize"
})
public class TTerritorialZone {

    @XmlElement(name = "PermittedUses", required = true)
    protected TTerritorialZone.PermittedUses permittedUses;
    @XmlElement(name = "LimitSize")
    protected TTerritorialZone.LimitSize limitSize;

    /**
     * Gets the value of the permittedUses property.
     * 
     * @return
     *     possible object is
     *     {@link TTerritorialZone.PermittedUses }
     *     
     */
    public TTerritorialZone.PermittedUses getPermittedUses() {
        return permittedUses;
    }

    /**
     * Sets the value of the permittedUses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTerritorialZone.PermittedUses }
     *     
     */
    public void setPermittedUses(TTerritorialZone.PermittedUses value) {
        this.permittedUses = value;
    }

    /**
     * Gets the value of the limitSize property.
     * 
     * @return
     *     possible object is
     *     {@link TTerritorialZone.LimitSize }
     *     
     */
    public TTerritorialZone.LimitSize getLimitSize() {
        return limitSize;
    }

    /**
     * Sets the value of the limitSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTerritorialZone.LimitSize }
     *     
     */
    public void setLimitSize(TTerritorialZone.LimitSize value) {
        this.limitSize = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Max" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="Min" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "max",
        "min"
    })
    public static class LimitSize {

        @XmlElement(name = "Max")
        protected BigDecimal max;
        @XmlElement(name = "Min")
        protected BigDecimal min;

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMax(BigDecimal value) {
            this.max = value;
        }

        /**
         * Gets the value of the min property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMin(BigDecimal value) {
            this.min = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PermittedUse" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TypePermittedUse" type="{}dPermitUse"/>
     *                   &lt;element name="LandUse" type="{}dUtilizations" minOccurs="0"/>
     *                   &lt;element name="PermittedUse">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="4000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "permittedUse"
    })
    public static class PermittedUses {

        @XmlElement(name = "PermittedUse", required = true)
        protected List<TTerritorialZone.PermittedUses.PermittedUse> permittedUse;

        /**
         * Gets the value of the permittedUse property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the permittedUse property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPermittedUse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTerritorialZone.PermittedUses.PermittedUse }
         * 
         * 
         */
        public List<TTerritorialZone.PermittedUses.PermittedUse> getPermittedUse() {
            if (permittedUse == null) {
                permittedUse = new ArrayList<TTerritorialZone.PermittedUses.PermittedUse>();
            }
            return this.permittedUse;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TypePermittedUse" type="{}dPermitUse"/>
         *         &lt;element name="LandUse" type="{}dUtilizations" minOccurs="0"/>
         *         &lt;element name="PermittedUse">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="4000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "typePermittedUse",
            "landUse",
            "permittedUse"
        })
        public static class PermittedUse {

            @XmlElement(name = "TypePermittedUse", required = true)
            protected String typePermittedUse;
            @XmlElement(name = "LandUse")
            protected String landUse;
            @XmlElement(name = "PermittedUse", required = true)
            protected String permittedUse;

            /**
             * Gets the value of the typePermittedUse property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTypePermittedUse() {
                return typePermittedUse;
            }

            /**
             * Sets the value of the typePermittedUse property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTypePermittedUse(String value) {
                this.typePermittedUse = value;
            }

            /**
             * Gets the value of the landUse property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLandUse() {
                return landUse;
            }

            /**
             * Sets the value of the landUse property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLandUse(String value) {
                this.landUse = value;
            }

            /**
             * Gets the value of the permittedUse property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPermittedUse() {
                return permittedUse;
            }

            /**
             * Sets the value of the permittedUse property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPermittedUse(String value) {
                this.permittedUse = value;
            }

        }

    }

}
