//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:25:35 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.zone.classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTitle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTitle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Visit_Purpose">
 *           &lt;simpleType>
 *             &lt;restriction base="{}dAction">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Request_Text" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Current_Changes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Cur_Change" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Cur_Change" type="{}dCurrentChanges"/>
 *                             &lt;element name="Cur_Change_Text" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="2000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Text_Old" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="2000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Text_New" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="2000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTitle", propOrder = {
    "visitPurpose",
    "requestText",
    "currentChanges"
})
public class TTitle {

    @XmlElement(name = "Visit_Purpose", required = true)
    protected String visitPurpose;
    @XmlElement(name = "Request_Text")
    protected String requestText;
    @XmlElement(name = "Current_Changes")
    protected TTitle.CurrentChanges currentChanges;

    /**
     * Gets the value of the visitPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitPurpose() {
        return visitPurpose;
    }

    /**
     * Sets the value of the visitPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitPurpose(String value) {
        this.visitPurpose = value;
    }

    /**
     * Gets the value of the requestText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestText() {
        return requestText;
    }

    /**
     * Sets the value of the requestText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestText(String value) {
        this.requestText = value;
    }

    /**
     * Gets the value of the currentChanges property.
     * 
     * @return
     *     possible object is
     *     {@link TTitle.CurrentChanges }
     *     
     */
    public TTitle.CurrentChanges getCurrentChanges() {
        return currentChanges;
    }

    /**
     * Sets the value of the currentChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTitle.CurrentChanges }
     *     
     */
    public void setCurrentChanges(TTitle.CurrentChanges value) {
        this.currentChanges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Cur_Change" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Cur_Change" type="{}dCurrentChanges"/>
     *                   &lt;element name="Cur_Change_Text" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Text_Old" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Text_New" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "curChange"
    })
    public static class CurrentChanges {

        @XmlElement(name = "Cur_Change", required = true)
        protected List<TTitle.CurrentChanges.CurChange> curChange;

        /**
         * Gets the value of the curChange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the curChange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCurChange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTitle.CurrentChanges.CurChange }
         * 
         * 
         */
        public List<TTitle.CurrentChanges.CurChange> getCurChange() {
            if (curChange == null) {
                curChange = new ArrayList<TTitle.CurrentChanges.CurChange>();
            }
            return this.curChange;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Cur_Change" type="{}dCurrentChanges"/>
         *         &lt;element name="Cur_Change_Text" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Text_Old" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Text_New" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "curChange",
            "curChangeText",
            "textOld",
            "textNew"
        })
        public static class CurChange {

            @XmlElement(name = "Cur_Change", required = true)
            protected String curChange;
            @XmlElement(name = "Cur_Change_Text")
            protected String curChangeText;
            @XmlElement(name = "Text_Old")
            protected String textOld;
            @XmlElement(name = "Text_New")
            protected String textNew;

            /**
             * Gets the value of the curChange property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurChange() {
                return curChange;
            }

            /**
             * Sets the value of the curChange property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurChange(String value) {
                this.curChange = value;
            }

            /**
             * Gets the value of the curChangeText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurChangeText() {
                return curChangeText;
            }

            /**
             * Sets the value of the curChangeText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurChangeText(String value) {
                this.curChangeText = value;
            }

            /**
             * Gets the value of the textOld property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextOld() {
                return textOld;
            }

            /**
             * Sets the value of the textOld property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextOld(String value) {
                this.textOld = value;
            }

            /**
             * Gets the value of the textNew property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextNew() {
                return textNew;
            }

            /**
             * Sets the value of the textNew property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextNew(String value) {
                this.textNew = value;
            }

        }

    }

}
