//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 06:25:35 PM NOVT 
//


package org.tomskgislab.vertex.xml.zem.zone.classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eDocument">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="02" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Request_ZoneToGKN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Title" type="{}tTitle"/>
 *                   &lt;element name="Declarant">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}tOwner">
 *                           &lt;sequence>
 *                             &lt;element name="Agent" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{}tPerson">
 *                                     &lt;sequence>
 *                                       &lt;element name="Appointment" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Zones">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Zone" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Cadastral_District" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AccountNumber" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Obj_Kind" type="{}dRealty"/>
 *                                       &lt;element name="CodeZone" type="{}dZone"/>
 *                                       &lt;element name="NameZone" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="NumberZone">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Index" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Authority" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element ref="{}Entity_Spatial" minOccurs="0"/>
 *                                       &lt;element name="Documents">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Document" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;extension base="{}tDocument">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="SourcePublication" minOccurs="0">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                 &lt;maxLength value="255"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/extension>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;choice>
 *                                         &lt;element name="TerritorialZone" type="{}tTerritorialZone"/>
 *                                         &lt;element name="SpecialZone" type="{}tSpecialZones"/>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Coord_Systems" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}Coord_System" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eDocument",
    "requestZoneToGKN"
})
@XmlRootElement(name = "ZoneToGKN")
public class ZoneToGKN {

    @XmlElement(required = true)
    protected ZoneToGKN.EDocument eDocument;
    @XmlElement(name = "Request_ZoneToGKN", required = true)
    protected ZoneToGKN.RequestZoneToGKN requestZoneToGKN;

    /**
     * Gets the value of the eDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneToGKN.EDocument }
     *     
     */
    public ZoneToGKN.EDocument getEDocument() {
        return eDocument;
    }

    /**
     * Sets the value of the eDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneToGKN.EDocument }
     *     
     */
    public void setEDocument(ZoneToGKN.EDocument value) {
        this.eDocument = value;
    }

    /**
     * Gets the value of the requestZoneToGKN property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneToGKN.RequestZoneToGKN }
     *     
     */
    public ZoneToGKN.RequestZoneToGKN getRequestZoneToGKN() {
        return requestZoneToGKN;
    }

    /**
     * Sets the value of the requestZoneToGKN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneToGKN.RequestZoneToGKN }
     *     
     */
    public void setRequestZoneToGKN(ZoneToGKN.RequestZoneToGKN value) {
        this.requestZoneToGKN = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="02" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EDocument {

        @XmlAttribute(name = "Version", required = true)
        protected String version;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            if (version == null) {
                return "02";
            } else {
                return version;
            }
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Title" type="{}tTitle"/>
     *         &lt;element name="Declarant">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}tOwner">
     *                 &lt;sequence>
     *                   &lt;element name="Agent" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{}tPerson">
     *                           &lt;sequence>
     *                             &lt;element name="Appointment" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Zones">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Zone" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Cadastral_District" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="AccountNumber" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Obj_Kind" type="{}dRealty"/>
     *                             &lt;element name="CodeZone" type="{}dZone"/>
     *                             &lt;element name="NameZone" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="NumberZone">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Index" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Authority" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="255"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element ref="{}Entity_Spatial" minOccurs="0"/>
     *                             &lt;element name="Documents">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Document" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;extension base="{}tDocument">
     *                                               &lt;sequence>
     *                                                 &lt;element name="SourcePublication" minOccurs="0">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                                       &lt;maxLength value="255"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/extension>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;choice>
     *                               &lt;element name="TerritorialZone" type="{}tTerritorialZone"/>
     *                               &lt;element name="SpecialZone" type="{}tSpecialZones"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Coord_Systems" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}Coord_System" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "declarant",
        "zones",
        "coordSystems"
    })
    public static class RequestZoneToGKN {

        @XmlElement(name = "Title", required = true)
        protected TTitle title;
        @XmlElement(name = "Declarant", required = true)
        protected ZoneToGKN.RequestZoneToGKN.Declarant declarant;
        @XmlElement(name = "Zones", required = true)
        protected ZoneToGKN.RequestZoneToGKN.Zones zones;
        @XmlElement(name = "Coord_Systems")
        protected ZoneToGKN.RequestZoneToGKN.CoordSystems coordSystems;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link TTitle }
         *     
         */
        public TTitle getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link TTitle }
         *     
         */
        public void setTitle(TTitle value) {
            this.title = value;
        }

        /**
         * Gets the value of the declarant property.
         * 
         * @return
         *     possible object is
         *     {@link ZoneToGKN.RequestZoneToGKN.Declarant }
         *     
         */
        public ZoneToGKN.RequestZoneToGKN.Declarant getDeclarant() {
            return declarant;
        }

        /**
         * Sets the value of the declarant property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZoneToGKN.RequestZoneToGKN.Declarant }
         *     
         */
        public void setDeclarant(ZoneToGKN.RequestZoneToGKN.Declarant value) {
            this.declarant = value;
        }

        /**
         * Gets the value of the zones property.
         * 
         * @return
         *     possible object is
         *     {@link ZoneToGKN.RequestZoneToGKN.Zones }
         *     
         */
        public ZoneToGKN.RequestZoneToGKN.Zones getZones() {
            return zones;
        }

        /**
         * Sets the value of the zones property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZoneToGKN.RequestZoneToGKN.Zones }
         *     
         */
        public void setZones(ZoneToGKN.RequestZoneToGKN.Zones value) {
            this.zones = value;
        }

        /**
         * Gets the value of the coordSystems property.
         * 
         * @return
         *     possible object is
         *     {@link ZoneToGKN.RequestZoneToGKN.CoordSystems }
         *     
         */
        public ZoneToGKN.RequestZoneToGKN.CoordSystems getCoordSystems() {
            return coordSystems;
        }

        /**
         * Sets the value of the coordSystems property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZoneToGKN.RequestZoneToGKN.CoordSystems }
         *     
         */
        public void setCoordSystems(ZoneToGKN.RequestZoneToGKN.CoordSystems value) {
            this.coordSystems = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}Coord_System" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "coordSystem"
        })
        public static class CoordSystems {

            @XmlElement(name = "Coord_System", required = true)
            protected List<CoordSystem> coordSystem;

            /**
             * Gets the value of the coordSystem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the coordSystem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCoordSystem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CoordSystem }
             * 
             * 
             */
            public List<CoordSystem> getCoordSystem() {
                if (coordSystem == null) {
                    coordSystem = new ArrayList<CoordSystem>();
                }
                return this.coordSystem;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}tOwner">
         *       &lt;sequence>
         *         &lt;element name="Agent" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{}tPerson">
         *                 &lt;sequence>
         *                   &lt;element name="Appointment" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "agent"
        })
        public static class Declarant
            extends TOwner
        {

            @XmlElement(name = "Agent")
            protected ZoneToGKN.RequestZoneToGKN.Declarant.Agent agent;

            /**
             * Gets the value of the agent property.
             * 
             * @return
             *     possible object is
             *     {@link ZoneToGKN.RequestZoneToGKN.Declarant.Agent }
             *     
             */
            public ZoneToGKN.RequestZoneToGKN.Declarant.Agent getAgent() {
                return agent;
            }

            /**
             * Sets the value of the agent property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZoneToGKN.RequestZoneToGKN.Declarant.Agent }
             *     
             */
            public void setAgent(ZoneToGKN.RequestZoneToGKN.Declarant.Agent value) {
                this.agent = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{}tPerson">
             *       &lt;sequence>
             *         &lt;element name="Appointment" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "appointment"
            })
            public static class Agent
                extends TPerson
            {

                @XmlElement(name = "Appointment")
                protected String appointment;

                /**
                 * Gets the value of the appointment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAppointment() {
                    return appointment;
                }

                /**
                 * Sets the value of the appointment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAppointment(String value) {
                    this.appointment = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Zone" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Cadastral_District" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="AccountNumber" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Obj_Kind" type="{}dRealty"/>
         *                   &lt;element name="CodeZone" type="{}dZone"/>
         *                   &lt;element name="NameZone" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="NumberZone">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Index" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Authority" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="255"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element ref="{}Entity_Spatial" minOccurs="0"/>
         *                   &lt;element name="Documents">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Document" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;extension base="{}tDocument">
         *                                     &lt;sequence>
         *                                       &lt;element name="SourcePublication" minOccurs="0">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                             &lt;maxLength value="255"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                       &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/extension>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;choice>
         *                     &lt;element name="TerritorialZone" type="{}tTerritorialZone"/>
         *                     &lt;element name="SpecialZone" type="{}tSpecialZones"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zone"
        })
        public static class Zones {

            @XmlElement(name = "Zone", required = true)
            protected List<ZoneToGKN.RequestZoneToGKN.Zones.Zone> zone;

            /**
             * Gets the value of the zone property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the zone property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getZone().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone }
             * 
             * 
             */
            public List<ZoneToGKN.RequestZoneToGKN.Zones.Zone> getZone() {
                if (zone == null) {
                    zone = new ArrayList<ZoneToGKN.RequestZoneToGKN.Zones.Zone>();
                }
                return this.zone;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Cadastral_District" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="AccountNumber" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Obj_Kind" type="{}dRealty"/>
             *         &lt;element name="CodeZone" type="{}dZone"/>
             *         &lt;element name="NameZone" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="NumberZone">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Index" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Authority" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="255"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element ref="{}Entity_Spatial" minOccurs="0"/>
             *         &lt;element name="Documents">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Document" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;extension base="{}tDocument">
             *                           &lt;sequence>
             *                             &lt;element name="SourcePublication" minOccurs="0">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                                   &lt;maxLength value="255"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                             &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/extension>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;choice>
             *           &lt;element name="TerritorialZone" type="{}tTerritorialZone"/>
             *           &lt;element name="SpecialZone" type="{}tSpecialZones"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cadastralDistrict",
                "accountNumber",
                "objKind",
                "codeZone",
                "nameZone",
                "numberZone",
                "index",
                "authority",
                "entitySpatial",
                "documents",
                "territorialZone",
                "specialZone"
            })
            public static class Zone {

                @XmlElement(name = "Cadastral_District", required = true)
                protected String cadastralDistrict;
                @XmlElement(name = "AccountNumber")
                protected String accountNumber;
                @XmlElement(name = "Obj_Kind", required = true)
                protected String objKind;
                @XmlElement(name = "CodeZone", required = true)
                protected String codeZone;
                @XmlElement(name = "NameZone")
                protected String nameZone;
                @XmlElement(name = "NumberZone", required = true)
                protected String numberZone;
                @XmlElement(name = "Index")
                protected String index;
                @XmlElement(name = "Authority")
                protected String authority;
                @XmlElement(name = "Entity_Spatial")
                protected EntitySpatial entitySpatial;
                @XmlElement(name = "Documents", required = true)
                protected ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents documents;
                @XmlElement(name = "TerritorialZone")
                protected TTerritorialZone territorialZone;
                @XmlElement(name = "SpecialZone")
                protected TSpecialZones specialZone;

                /**
                 * Gets the value of the cadastralDistrict property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCadastralDistrict() {
                    return cadastralDistrict;
                }

                /**
                 * Sets the value of the cadastralDistrict property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCadastralDistrict(String value) {
                    this.cadastralDistrict = value;
                }

                /**
                 * Gets the value of the accountNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccountNumber() {
                    return accountNumber;
                }

                /**
                 * Sets the value of the accountNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccountNumber(String value) {
                    this.accountNumber = value;
                }

                /**
                 * Gets the value of the objKind property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getObjKind() {
                    return objKind;
                }

                /**
                 * Sets the value of the objKind property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setObjKind(String value) {
                    this.objKind = value;
                }

                /**
                 * Gets the value of the codeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeZone() {
                    return codeZone;
                }

                /**
                 * Sets the value of the codeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeZone(String value) {
                    this.codeZone = value;
                }

                /**
                 * Gets the value of the nameZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNameZone() {
                    return nameZone;
                }

                /**
                 * Sets the value of the nameZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNameZone(String value) {
                    this.nameZone = value;
                }

                /**
                 * Gets the value of the numberZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNumberZone() {
                    return numberZone;
                }

                /**
                 * Sets the value of the numberZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNumberZone(String value) {
                    this.numberZone = value;
                }

                /**
                 * Gets the value of the index property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIndex() {
                    return index;
                }

                /**
                 * Sets the value of the index property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIndex(String value) {
                    this.index = value;
                }

                /**
                 * Gets the value of the authority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthority() {
                    return authority;
                }

                /**
                 * Sets the value of the authority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthority(String value) {
                    this.authority = value;
                }

                /**
                 * Gets the value of the entitySpatial property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link EntitySpatial }
                 *     
                 */
                public EntitySpatial getEntitySpatial() {
                    return entitySpatial;
                }

                /**
                 * Sets the value of the entitySpatial property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link EntitySpatial }
                 *     
                 */
                public void setEntitySpatial(EntitySpatial value) {
                    this.entitySpatial = value;
                }

                /**
                 * Gets the value of the documents property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents }
                 *     
                 */
                public ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents getDocuments() {
                    return documents;
                }

                /**
                 * Sets the value of the documents property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents }
                 *     
                 */
                public void setDocuments(ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents value) {
                    this.documents = value;
                }

                /**
                 * Gets the value of the territorialZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TTerritorialZone }
                 *     
                 */
                public TTerritorialZone getTerritorialZone() {
                    return territorialZone;
                }

                /**
                 * Sets the value of the territorialZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TTerritorialZone }
                 *     
                 */
                public void setTerritorialZone(TTerritorialZone value) {
                    this.territorialZone = value;
                }

                /**
                 * Gets the value of the specialZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TSpecialZones }
                 *     
                 */
                public TSpecialZones getSpecialZone() {
                    return specialZone;
                }

                /**
                 * Sets the value of the specialZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TSpecialZones }
                 *     
                 */
                public void setSpecialZone(TSpecialZones value) {
                    this.specialZone = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Document" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;extension base="{}tDocument">
                 *                 &lt;sequence>
                 *                   &lt;element name="SourcePublication" minOccurs="0">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *                         &lt;maxLength value="255"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                   &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/extension>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "document"
                })
                public static class Documents {

                    @XmlElement(name = "Document", required = true)
                    protected List<ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document> document;

                    /**
                     * Gets the value of the document property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the document property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getDocument().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document }
                     * 
                     * 
                     */
                    public List<ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document> getDocument() {
                        if (document == null) {
                            document = new ArrayList<ZoneToGKN.RequestZoneToGKN.Zones.Zone.Documents.Document>();
                        }
                        return this.document;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;extension base="{}tDocument">
                     *       &lt;sequence>
                     *         &lt;element name="SourcePublication" minOccurs="0">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;maxLength value="255"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="Quantity" type="{}tQuantity" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/extension>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "sourcePublication",
                        "quantity"
                    })
                    public static class Document
                        extends TDocument
                    {

                        @XmlElement(name = "SourcePublication")
                        protected String sourcePublication;
                        @XmlElement(name = "Quantity")
                        protected TQuantity quantity;

                        /**
                         * Gets the value of the sourcePublication property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSourcePublication() {
                            return sourcePublication;
                        }

                        /**
                         * Sets the value of the sourcePublication property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSourcePublication(String value) {
                            this.sourcePublication = value;
                        }

                        /**
                         * Gets the value of the quantity property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link TQuantity }
                         *     
                         */
                        public TQuantity getQuantity() {
                            return quantity;
                        }

                        /**
                         * Sets the value of the quantity property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link TQuantity }
                         *     
                         */
                        public void setQuantity(TQuantity value) {
                            this.quantity = value;
                        }

                    }

                }

            }

        }

    }

}
